angular.module('JOJO', ['ngRoute', 'datatables'])
.service('andSearchService', ANDSearchService)
.filter('andSearchFilter', ANDSearchFilter)
.controller('ANDSearchController', ANDSearchController)
.controller('AngularWayWithOptionsCtrl', AngularWayWithOptionsCtrl)