<template>
  <vue-pixel-board :seed="seed"/>
</template>

<script>
  import VuePixelBoard from '@/components/vue-pixel/VuePixelBoard';

  const BG = '#555555';
  const BLUE = '#008cc8'; // 0 140 200
  const SKY = '#2dbae8';  // 45 186 232
  const LIGHT_GRAY = '#f5f5f5';
  const WHITE = '#FFFFFF';
  const HAIR = '#50340a';
  const SKIN = '#fec878';
  const YELLOW = '#fbed29';
  const PINK = '#e75e00';

  export default {
    name: 'vue-pixel',
    components: {
      VuePixelBoard,
    },
    data() {
      return {
        seed: [
          [
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BLUE, after: HAIR },
            { before: BLUE, after: HAIR },
            { before: BLUE, after: HAIR },
            { before: BLUE, after: HAIR },
            { before: BLUE, after: HAIR },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
          ],
          [
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BLUE, after: HAIR },
            { before: BLUE, after: HAIR },
            { before: BLUE, after: HAIR },
            { before: BLUE, after: HAIR },
            { before: BLUE, after: HAIR },
            { before: BLUE, after: HAIR },
            { before: BLUE, after: HAIR },
            { before: BLUE, after: BG },
            { before: BLUE, after: BG },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
          ],
          [
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: HAIR, static: true },
            { before: HAIR, static: true },
            { before: HAIR, static: true },
            { before: SKIN, static: true },
            { before: HAIR, static: true },
            { before: SKIN, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
          ],
          [
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: HAIR, static: true },
            { before: SKIN, static: true },
            { before: HAIR, static: true },
            { before: SKIN, static: true },
            { before: SKIN, static: true },
            { before: HAIR, static: true },
            { before: SKIN, static: true },
            { before: SKIN, static: true },
            { before: SKIN, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
          ],
          [
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: HAIR, static: true },
            { before: SKIN, static: true },
            { before: HAIR, static: true },
            { before: HAIR, static: true },
            { before: SKIN, static: true },
            { before: SKIN, static: true },
            { before: HAIR, after: SKIN },
            { before: SKIN, static: true },
            { before: SKIN, static: true },
            { before: SKIN, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
          ],
          [
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: HAIR, static: true },
            { before: HAIR, static: true },
            { before: SKIN, static: true },
            { before: SKIN, static: true },
            { before: SKIN, static: true },
            { before: HAIR, after: SKIN },
            { before: HAIR, after: PINK },
            { before: HAIR, after: PINK },
            { before: HAIR, after: SKIN },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
          ],
          [
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: SKIN, static: true },
            { before: SKIN, static: true },
            { before: SKIN, static: true },
            { before: SKIN, static: true },
            { before: SKIN, static: true },
            { before: SKIN, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
          ],
          [
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: SKY, after: SKIN },
            { before: SKY, after: SKIN },
            { before: SKY, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: SKY, after: SKIN },
            { before: SKY, after: SKIN },
            { before: SKY, after: SKIN },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
          ],
          [
            { before: BG, static: true },
            { before: BG, static: true },
            { before: SKY, after: SKIN },
            { before: SKY, after: SKIN },
            { before: SKY, after: SKIN },
            { before: SKY, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: SKY, after: SKIN },
            { before: SKY, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: SKY, after: SKIN },
            { before: SKY, after: SKIN },
            { before: SKY, after: SKIN },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
          ],
          [
            { before: BG, static: true },
            { before: SKY, after: SKIN },
            { before: SKY, after: SKIN },
            { before: SKY, after: SKIN },
            { before: SKY, after: SKIN },
            { before: SKY, after: PINK },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: SKY, after: PINK },
            { before: SKY, after: SKIN },
            { before: SKY, after: SKIN },
            { before: SKY, after: SKIN },
            { before: BG, static: true },
            { before: BG, static: true },
          ],
          [
            { before: BG, static: true },
            { before: LIGHT_GRAY, after: SKIN },
            { before: WHITE, after: SKIN },
            { before: WHITE, after: SKIN },
            { before: SKY, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: YELLOW, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: YELLOW, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: SKY, after: SKIN },
            { before: WHITE, after: SKIN },
            { before: WHITE, after: SKIN },
            { before: WHITE, after: SKIN },
            { before: BG, static: true },
          ],
          [
            { before: BG, static: true },
            { before: LIGHT_GRAY, after: SKIN },
            { before: WHITE, after: SKIN },
            { before: WHITE, after: SKIN },
            { before: WHITE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: WHITE, after: SKIN },
            { before: WHITE, after: SKIN },
            { before: WHITE, after: SKIN },
            { before: WHITE, after: SKIN },
            { before: BG, static: true },
          ],
          [
            { before: BG, static: true },
            { before: LIGHT_GRAY, after: SKIN },
            { before: WHITE, after: SKIN },
            { before: WHITE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: WHITE, after: SKIN },
            { before: WHITE, after: SKIN },
            { before: WHITE, after: SKIN },
            { before: BG, static: true },
          ],
          [
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
          ],
          [
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: SKY, after: SKIN },
            { before: SKY, after: SKIN },
            { before: SKY, after: SKIN },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: SKY, after: SKIN },
            { before: SKY, after: SKIN },
            { before: SKY, after: SKIN },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
          ],
          [
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BG, static: true },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BLUE, after: SKIN },
            { before: BG, static: true },
            { before: BG, static: true },
          ],
        ],
      };
    },
  };
</script>

<style scoped>

</style>
