name: Before Merge
on:
  push:
    branches-ignore:
      - master
      - release/*

jobs:
  lint-test-build:
    name: Lint, Unit Test and Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Read .node-version
        id: node-version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.node-version
      - name: Use Node.js ${{ steps.node-version.outputs.content }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node-version.outputs.content }}
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Generate
        run: npm run generate
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
          if-no-files-found: error
