name: Before Merge
on:
  push:
    branches-ignore:
      - master
      - release/*

jobs:
  lint-test-build:
    name: Lint, Unit Test and Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Read .node-version
        id: node-version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.node-version
      - name: Use Node.js ${{ steps.node-version.outputs.content }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node-version.outputs.content }}
      - name: Install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-v${{ matrix.node-version }}-pkg-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
      - name: Lint and Unit Test
        run: |
          npm run lint
          npm run test
      - name: Generate
        run: npm run generate
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
          if-no-files-found: error

  test-e2e:
    name: E2E Test

    needs: lint-test-build

    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [ chrome, firefox, edge ]

    steps:
      - uses: actions/checkout@v2
      - name: Read .node-version
        id: node-version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.node-version
      - name: Use Node.js ${{ steps.node-version.outputs.content }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node-version.outputs.content }}
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: E2E by Cypress
        uses: cypress-io/github-action@v2
        with:
          browser: ${{ matrix.browser }}
          command: npm run e2e:ci
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-${{ matrix.browser }}
          path: |
            cypress/videos
            cypress/screenshots
