name: Deploy
on:
  push:
    branches:
      - master
      - release/*

jobs:
  lint-build-test:
    name: Lint & Build & Test

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.10.0]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: test and generate
        run: |
          npm ci
          npm run lint
          npm run test
          npm run generate
        env:
          CI: true
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy:
    name: Deploy

    needs: lint-build-test

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.10.0]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

