name: Release
on:
  push:
    branches:
      - master
      - release/*

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Read .node-version
        id: node-version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.node-version
      - name: Use Node.js ${{ steps.node-version.outputs.content }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node-version.outputs.content }}
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Generate
        run: npm run generate
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
