name: Test
on: [push]

jobs:
  lint-build-test:
    name: Lint & Build & Test

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15.3]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: test and generate
        run: |
          npm ci
          npm run lint
          npm run test
          npm run generate
        env:
          CI: true
      - name: E2E by Cypress
        uses: cypress-io/github-action@v2
        with:
          command: npm run e2e:ci
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress
          path: |
            cypress/videos
            cypress/screenshots
      - uses: actions/upload-artifact@v2
        with:
          name: app
          path: dist
          if-no-files-found: error
